// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel():Promise<void>;

export function DeleteCourse(arg1:number):Promise<Record<string, any>>;

export function Download(arg1:Array<number>):Promise<void>;

export function GetCourses():Promise<Array<Record<string, any>>>;

export function GetDownloadDir():Promise<string>;

export function GoBack():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<void>;

export function OpenCourseFolder(arg1:number):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function SelectPlatform(arg1:string):Promise<Record<string, any>>;

export function SelectSubgroup(arg1:number):Promise<Record<string, any>>;
