// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function DeleteCourse(arg1) {
  return window['go']['main']['App']['DeleteCourse'](arg1);
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function GetCourses() {
  return window['go']['main']['App']['GetCourses']();
}

export function GetDownloadDir() {
  return window['go']['main']['App']['GetDownloadDir']();
}

export function GoBack() {
  return window['go']['main']['App']['GoBack']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenCourseFolder(arg1) {
  return window['go']['main']['App']['OpenCourseFolder'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function SelectPlatform(arg1) {
  return window['go']['main']['App']['SelectPlatform'](arg1);
}

export function SelectSubgroup(arg1) {
  return window['go']['main']['App']['SelectSubgroup'](arg1);
}
